### PR TITLE
Chapter 3.2 claw-back vault case study.

### PR DESCRIPTION
**Pull request by jachiang**
TODO:
- [ ] Complete Solutions.

### CODE REVIEW

**Comment by bitschmidty** [comment]
@jnewbery Do you think we should currently pursue this as a post workshop effort?

**Comment by jnewbery** [comment]
I don't think this is a priority, but I'm happy to review it once James thinks it's ready.

**Comment by jachiang** [comment]
Will work on this, but would wait for the resolution of [#92](https://github.com/bitcoinops/taproot-workshop/issues/92#issue-499132570) before merging this one, as it relies on generating a revaulting transaction chain: this would be less tedious with a taptroot tx constructor method.

**Comment by jnewbery** [comment]
#92 is merged

**Comment by bitschmidty** [comment]
Going to close this for inactivity for now. If @jachiang has the itch to reopen it, we can revisit then.

**Pull request closed without merging**
