### PR TITLE
Sync Colab branch with master

### PR DESCRIPTION
**Pull request by mmilata**
Issue #172. This is a result of `git merge master` and resolving the conflict in `README.md`. Only checked `1.1-schnorr-signatures.ipynb` but it seems to work fine.

### CODE REVIEW

**Comment by 0xB10C** [comment]
Successfully tested both 2.0.2 and 2.0.6 on a local Jupyter notebook with a self-compiled `bitcoind`.

The issue with the Colab setup seems to be that this line is commented out.

https://github.com/bitcoinops/taproot-workshop/blob/7e0e628a0e12bbcf39bb624118544b5d796409d8/setup-colab-env.sh#L34

The test framework does not create the default wallet (see https://github.com/bitcoinops/taproot-workshop/pull/168/commits/8e054de3aa19f0f31f5ca46dd27fc84f1bceefa1#diff-bcbd83e29988ebae39a140201447e86bc719b60278bc44dab4f23efa13af7580R100-R102) when it thinks the wallet is not compiled in (set in `test/config.ini` when running `./configure`). I'm not sure why (or if?) this worked in the past. With no `#` before `ENABLE_WALLET=true` this successfully runs in Colab.

**Comment by mmilata** [comment]
Yup, that seems to work. Thanks @0xB10C!

**Comment by 0xB10C** [comment]
Successfully tested this PR on Colab by running this notebook https://colab.research.google.com/github/mmilata/taproot-workshop/blob/colab-update/2.0-taproot-introduction.ipynb and manually changing the the `setup-colab-env.sh` script URL:

``` diff
- !curl -o- -s -S -L https://raw.githubusercontent.com/bitcoinops/taproot-workshop/Colab/setup-colab-env.sh | bash
+ !curl -o- -s -S -L https://raw.githubusercontent.com/mmilata/taproot-workshop/colab-update/setup-colab-env.sh | bash
```

Not sure why GitHub is complaining `This branch has conflicts that must be resolved`.

**Comment by mmilata** [comment]
It's because @jnewbery asked me to rebase the Colab changes on top of master but GitHub thinks we're gonna merge it.

**Comment by mmilata** [comment]
Ping @jnewbery, should be working now, wanna force-push it? Can't wait to spam my colleagues with the workshop
:smiley:

**Comment by jnewbery** [comment]
> Ping @jnewbery, should be working now, wanna force-push it? Can't wait to spam my colleagues with the workshop

Done! Thanks so much @mmilata! (and @0xB10C for testing)

**Pull request merged**
