### PR TITLE
Fixed capitalization in segwit v1 images.

### PR DESCRIPTION
**Pull request by jachiang**
Addresses [#51](https://github.com/bitcoinops/taproot-workshop/issues/51#issue-496703928) and segwit_version1_1.jpg/svg.

### CODE REVIEW

**Comment by jnewbery** [comment]
Thanks James. Looks good. One suggested change:

"Segwit V1 address" to "Segwit v1 address" (we use lowercase v1 throughout the notebooks).

**Comment by jachiang** [comment]
> Thanks James. Looks good. One suggested change:
> 
> "Segwit V1 address" to "Segwit v1 address" (we use lowercase v1 throughout the notebooks).

Fixed. 
V1 remains capitalized in the image title(s), though?

**Comment by jachiang** [comment]
Rebased on master.

**Comment by jnewbery** [comment]
> V1 remains capitalized in the image title(s), though?

Yes, if the entire title is capitalized.

**Comment by jnewbery** [comment]
Looks good. Thanks!

**Pull request merged**
